name: Build APKs

on:
  release:
    types: [published]

jobs:
  build:
    name: Upload APKs to release
    runs-on: ubuntu-latest
    steps:
      # Download code from repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup JDK
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Setup Android SDK
      - name: Setup Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.1

      # Setup keystore
      - name: Setup keystore
        env:
          KEYSTORE_DATA: ${{ secrets.KEYSTORE_DATA }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
        run: |
          echo "$KEYSTORE_DATA" | base64 -d > keystore.jks
          echo "keystoreFile=$PWD/keystore.jks" >> gradle.properties
          echo "keystoreAlias=mainkey" >> gradle.properties
          echo "keystorePassword=$KEYSTORE_PASS" >> gradle.properties

      # Execute Gradle build
      - name: Build project
        run: chmod +x ./gradlew && ./gradlew --no-daemon assembleSignedRelease

      # Upload assets
      - name: Add APKs to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for f in app/build/outputs/apk/signedRelease/*.apk; do
            echo "Uploading $f ..."
            gh release upload ${GITHUB_REF##*/} "$f"
          done
